version: '3'

services:
  shop:
    container_name: sw6-simple-api
    image: dockware/dev:6.4.20.2
    ports:
#      - "22:22"     # ssh
      - "80:80"     # apache2
      - "3306:3306" # mysql
    volumes:
      - ".:/var/www/html/custom/plugins/sw6"
      - .coverage:/opt/phpstorm-coverage:rw
    networks:
      - sw6-simple-api
    environment:
      - PHP_VERSION=8.1
      - XDEBUG_ENABLED=1
      - XDEBUG_MODE=debug,coverage
      # Für Remote-Setup benötigt: hier müsste IP des Laptops eingetragen werden
      # - XDEBUG_REMOTE_HOST=

networks:
  sw6-simple-api:
    external: false